// Code generated by MockGen. DO NOT EDIT.
// Source: department.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	models "github.com/BountyM/hitalentTestTask/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockDepartment is a mock of Department interface.
type MockDepartment struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentMockRecorder
}

// MockDepartmentMockRecorder is the mock recorder for MockDepartment.
type MockDepartmentMockRecorder struct {
	mock *MockDepartment
}

// NewMockDepartment creates a new mock instance.
func NewMockDepartment(ctrl *gomock.Controller) *MockDepartment {
	mock := &MockDepartment{ctrl: ctrl}
	mock.recorder = &MockDepartmentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartment) EXPECT() *MockDepartmentMockRecorder {
	return m.recorder
}

// CreateDepartment mocks base method.
func (m *MockDepartment) CreateDepartment(department *models.Department) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDepartment", department)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDepartment indicates an expected call of CreateDepartment.
func (mr *MockDepartmentMockRecorder) CreateDepartment(department interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDepartment", reflect.TypeOf((*MockDepartment)(nil).CreateDepartment), department)
}

// CreateEmployee mocks base method.
func (m *MockDepartment) CreateEmployee(employee *models.Employee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmployee", employee)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEmployee indicates an expected call of CreateEmployee.
func (mr *MockDepartmentMockRecorder) CreateEmployee(employee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmployee", reflect.TypeOf((*MockDepartment)(nil).CreateEmployee), employee)
}

// DeleteDepartment mocks base method.
func (m *MockDepartment) DeleteDepartment(departmentID int, mode string, reassignToID *int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDepartment", departmentID, mode, reassignToID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDepartment indicates an expected call of DeleteDepartment.
func (mr *MockDepartmentMockRecorder) DeleteDepartment(departmentID, mode, reassignToID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDepartment", reflect.TypeOf((*MockDepartment)(nil).DeleteDepartment), departmentID, mode, reassignToID)
}

// Exists mocks base method.
func (m *MockDepartment) Exists(departmentID int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", departmentID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockDepartmentMockRecorder) Exists(departmentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockDepartment)(nil).Exists), departmentID)
}

// GetDepartment mocks base method.
func (m *MockDepartment) GetDepartment(departmentID, depth int, includeEmployees bool) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDepartment", departmentID, depth, includeEmployees)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDepartment indicates an expected call of GetDepartment.
func (mr *MockDepartmentMockRecorder) GetDepartment(departmentID, depth, includeEmployees interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDepartment", reflect.TypeOf((*MockDepartment)(nil).GetDepartment), departmentID, depth, includeEmployees)
}

// UpdateDepartment mocks base method.
func (m *MockDepartment) UpdateDepartment(departmentID int, name *string, parentID *int) (*models.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDepartment", departmentID, name, parentID)
	ret0, _ := ret[0].(*models.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDepartment indicates an expected call of UpdateDepartment.
func (mr *MockDepartmentMockRecorder) UpdateDepartment(departmentID, name, parentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDepartment", reflect.TypeOf((*MockDepartment)(nil).UpdateDepartment), departmentID, name, parentID)
}
